MangoStore/Models/CouponDto.cs
namespace MangoStore.Models
{
	
		public class CouponDto
		{
			public int CouponId { get; set; }
			public string CouponCode { get; set; }
			public double DiscountAmount { get; set; }
			public int MinAmount { get; set; }

		}
	
}

MangoStore/Models/ErrorViewModel.cs
namespace MangoStore.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MangoStore/Controllers/CouponController.cs
using MangoStore.Models;
using MangoStore.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MangoStore.Controllers
{
	public class CouponController : Controller
	{
		private readonly ICouponSevice _couponSevice;
		public CouponController(ICouponSevice couponSevice)
		{
			_couponSevice = couponSevice;
		}

		public async Task<IActionResult> CouponIndex()
		{
			List<CouponDto> coupons = new();
			var response = await _couponSevice.GetAllCoupon();
			Console.WriteLine(response);
			if (response != null && response.isSuccess)
			{
				coupons = JsonSerializer.Deserialize<List<CouponDto>>(response.data.ToString() ?? string.Empty, new JsonSerializerOptions
				{
					PropertyNameCaseInsensitive = true
				});
			}
			return View(coupons);
		}

		public async Task<IActionResult> CreateCoupon()
		{
			CouponDto couponDto = new();
			return View(couponDto);			
		}
	}
}

MangoStore/Controllers/HomeController.cs
using MangoStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MangoStore.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MangoStore/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>																																																																									
<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Coupons List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Coupon Code 

					</th>
					<th>
						Discount Amount
					</th>
					<th>
						Minimum Amount
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody class="text-bg-dark">
				@foreach (var item in Model) {
				<tr>
					<td>
						@item.CouponCode
					</td>
					<td>
						@(item.DiscountAmount)
					</td>
					<td>
						@(item.MinAmount)
					</td>
					<td>
						<a class="btn btn-danger">
							
							<i class="bi bi-trash"></i>
						</a>
					</td>
				</tr>
			}
			</tbody>
		</table>

	</div>
</div>

MangoStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MangoStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangoStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MangoStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">MangoStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupons</a></li>
                                <li><hr class="dropdown-divider"></li>
                                
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted center">
        <div class="text-center">
            <p>Mango <i class="bi bi-tencent-qq"></i> Store </p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>